twig:
    file_name_pattern: '*.twig'
    # default_path: '%kernel.project_dir%/templates'
    # error_controller: App\Controller\ErrorController::show

when@test:
    twig:
        strict_variables: true
